### ISSUE TITLE
急

### ISSUE THREAD

**Issue by CQZhouJia** [jinht/BannerScrollView#4]
能留一个联系方式加好友吗有点问题请教你

**Comment by jinht** [comment]
留下问题

**Comment by CQZhouJia** [comment]
我也是无限循环不过我这个视图上不单单能看见一张图片 可以看到1张图和接下来的一张图的一部分 然后我无限循环过程中一圈后 有点抖动 我中间还有点动画&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JZ"<notifications@github.com&gt;; 
发送时间: 2019年12月5日(星期四) 下午2:04
收件人: "jinht/BannerScrollView"<BannerScrollView@noreply.github.com&gt;; 
抄送: "周佳"<624891406@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jinht/BannerScrollView] 急 (#4)




留下问题
